"""AlphaScan ortak piyasa evrenleri.

BIST Katılım listeleri ve kripto tarama evreni bu dosyadan okunur.
"""

BIST_KATILIM_AS_OF = "16/07/2026"
CRYPTO_AS_OF = "2026-07-23"

KATILIM_TUM = [
    {"kod": "AAGYO", "sembol": "AAGYO.IS", "ad": "AGAOGLU GMYO", "arindirma": None},
    {"kod": "ACSEL", "sembol": "ACSEL.IS", "ad": "ACIPAYAM SELULOZ", "arindirma": None},
    {"kod": "AHGAZ", "sembol": "AHGAZ.IS", "ad": "AHLATCI DOGALGAZ", "arindirma": None},
    {"kod": "AHSGY", "sembol": "AHSGY.IS", "ad": "AHES GMYO", "arindirma": None},
    {"kod": "AKFYE", "sembol": "AKFYE.IS", "ad": "AKFEN YEN. ENERJI", "arindirma": None},
    {"kod": "AKHAN", "sembol": "AKHAN.IS", "ad": "AKHAN UN", "arindirma": None},
    {"kod": "ALBRK", "sembol": "ALBRK.IS", "ad": "ALBARAKA TURK", "arindirma": None},
    {"kod": "ALCTL", "sembol": "ALCTL.IS", "ad": "ALCATEL LUCENT TELETAS", "arindirma": None},
    {"kod": "ALFAS", "sembol": "ALFAS.IS", "ad": "ALFA SOLAR ENERJI", "arindirma": None},
    {"kod": "ALKA", "sembol": "ALKA.IS", "ad": "ALKIM KAGIT", "arindirma": None},
    {"kod": "ALKIM", "sembol": "ALKIM.IS", "ad": "ALKIM KIMYA", "arindirma": None},
    {"kod": "ALKLC", "sembol": "ALKLC.IS", "ad": "ALTINKILIC GIDA VE SUT", "arindirma": None},
    {"kod": "ALTNY", "sembol": "ALTNY.IS", "ad": "ALTINAY SAVUNMA", "arindirma": None},
    {"kod": "ALVES", "sembol": "ALVES.IS", "ad": "ALVES KABLO", "arindirma": None},
    {"kod": "ANGEN", "sembol": "ANGEN.IS", "ad": "ANATOLIA TANI VE BIYOTEKNOLOJI", "arindirma": None},
    {"kod": "ARASE", "sembol": "ARASE.IS", "ad": "DOGU ARAS ENERJI", "arindirma": None},
    {"kod": "ARDYZ", "sembol": "ARDYZ.IS", "ad": "ARD BILISIM TEKNOLOJILERI", "arindirma": None},
    {"kod": "ARENA", "sembol": "ARENA.IS", "ad": "ARENA BILGISAYAR", "arindirma": None},
    {"kod": "ARFYE", "sembol": "ARFYE.IS", "ad": "ARF BIO YENILENEBILIR ENERJI", "arindirma": None},
    {"kod": "ASELS", "sembol": "ASELS.IS", "ad": "ASELSAN", "arindirma": None},
    {"kod": "ATAKP", "sembol": "ATAKP.IS", "ad": "ATAKEY PATATES", "arindirma": None},
    {"kod": "ATATP", "sembol": "ATATP.IS", "ad": "ATP YAZILIM", "arindirma": None},
    {"kod": "AVPGY", "sembol": "AVPGY.IS", "ad": "AVRUPAKENT GMYO", "arindirma": None},
    {"kod": "AYEN", "sembol": "AYEN.IS", "ad": "AYEN ENERJI", "arindirma": None},
    {"kod": "BAHKM", "sembol": "BAHKM.IS", "ad": "BAHADIR KIMYA", "arindirma": None},
    {"kod": "BAKAB", "sembol": "BAKAB.IS", "ad": "BAK AMBALAJ", "arindirma": None},
    {"kod": "BASGZ", "sembol": "BASGZ.IS", "ad": "BASKENT DOGALGAZ GMYO", "arindirma": None},
    {"kod": "BAYRK", "sembol": "BAYRK.IS", "ad": "BAYRAK TABAN SANAYI", "arindirma": None},
    {"kod": "BEGYO", "sembol": "BEGYO.IS", "ad": "BATI EGE GMYO", "arindirma": None},
    {"kod": "BERA", "sembol": "BERA.IS", "ad": "BERA HOLDING", "arindirma": None},
    {"kod": "BESTE", "sembol": "BESTE.IS", "ad": "BEST BRANDS ENERJI", "arindirma": None},
    {"kod": "BETAE", "sembol": "BETAE.IS", "ad": "BETA ENERJI VE TEKNOLOJI", "arindirma": None},
    {"kod": "BIENY", "sembol": "BIENY.IS", "ad": "BIEN YAPI URUNLERI", "arindirma": None},
    {"kod": "BIMAS", "sembol": "BIMAS.IS", "ad": "BIM MAGAZALAR", "arindirma": None},
    {"kod": "BINBN", "sembol": "BINBN.IS", "ad": "BIN ULASIM TEKNOLOJILERI", "arindirma": None},
    {"kod": "BINHO", "sembol": "BINHO.IS", "ad": "1000 YATIRIMLAR HOL.", "arindirma": None},
    {"kod": "BMSTL", "sembol": "BMSTL.IS", "ad": "BMS BIRLESIK METAL", "arindirma": None},
    {"kod": "BORSK", "sembol": "BORSK.IS", "ad": "BOR SEKER", "arindirma": None},
    {"kod": "BOSSA", "sembol": "BOSSA.IS", "ad": "BOSSA", "arindirma": None},
    {"kod": "BRISA", "sembol": "BRISA.IS", "ad": "BRISA", "arindirma": None},
    {"kod": "BRKSN", "sembol": "BRKSN.IS", "ad": "BERKOSAN YALITIM", "arindirma": None},
    {"kod": "BRLSM", "sembol": "BRLSM.IS", "ad": "BIRLESIM MUHENDISLIK", "arindirma": None},
    {"kod": "BSOKE", "sembol": "BSOKE.IS", "ad": "BATICIM CIMENTO", "arindirma": None},
    {"kod": "BUCIM", "sembol": "BUCIM.IS", "ad": "BURSA CIMENTO", "arindirma": None},
    {"kod": "BURCE", "sembol": "BURCE.IS", "ad": "BURCELIK", "arindirma": None},
    {"kod": "BURVA", "sembol": "BURVA.IS", "ad": "BURCELIK VANA", "arindirma": None},
    {"kod": "BYDNR", "sembol": "BYDNR.IS", "ad": "BAYDONER RESTORANLARI", "arindirma": None},
    {"kod": "CANTE", "sembol": "CANTE.IS", "ad": "CAN2 TERMIK", "arindirma": None},
    {"kod": "CATES", "sembol": "CATES.IS", "ad": "CATES ELEKTRIK", "arindirma": None},
    {"kod": "CELHA", "sembol": "CELHA.IS", "ad": "CELIK HALAT", "arindirma": None},
    {"kod": "CEMTS", "sembol": "CEMTS.IS", "ad": "CEMTAS", "arindirma": None},
    {"kod": "CEMZY", "sembol": "CEMZY.IS", "ad": "CEM ZEYTIN", "arindirma": None},
    {"kod": "CIMSA", "sembol": "CIMSA.IS", "ad": "CIMSA", "arindirma": None},
    {"kod": "CMBTN", "sembol": "CMBTN.IS", "ad": "CIMBETON", "arindirma": None},
    {"kod": "COSMO", "sembol": "COSMO.IS", "ad": "COSMOS YAT. HOLDING", "arindirma": None},
    {"kod": "CVKMD", "sembol": "CVKMD.IS", "ad": "CVK MADEN", "arindirma": None},
    {"kod": "CWENE", "sembol": "CWENE.IS", "ad": "CW ENERJI", "arindirma": None},
    {"kod": "DAPGM", "sembol": "DAPGM.IS", "ad": "DAP GAYRIMENKUL", "arindirma": None},
    {"kod": "DARDL", "sembol": "DARDL.IS", "ad": "DARDANEL", "arindirma": None},
    {"kod": "DCTTR", "sembol": "DCTTR.IS", "ad": "DCT TRADING DIS TICARET", "arindirma": None},
    {"kod": "DENGE", "sembol": "DENGE.IS", "ad": "DENGE HOLDING", "arindirma": None},
    {"kod": "DESPC", "sembol": "DESPC.IS", "ad": "DESPEC BILGISAYAR", "arindirma": None},
    {"kod": "DGATE", "sembol": "DGATE.IS", "ad": "DATAGATE BILGISAYAR", "arindirma": None},
    {"kod": "DITAS", "sembol": "DITAS.IS", "ad": "DITAS BDY", "arindirma": None},
    {"kod": "DMSAS", "sembol": "DMSAS.IS", "ad": "DEMISAS DOKUM", "arindirma": None},
    {"kod": "DNISI", "sembol": "DNISI.IS", "ad": "DINAMIK ISI MAKINA YALITIM", "arindirma": None},
    {"kod": "DOFER", "sembol": "DOFER.IS", "ad": "DOFER YAPI MALZEMELERI", "arindirma": None},
    {"kod": "DOFRB", "sembol": "DOFRB.IS", "ad": "DOF ROBOTIK", "arindirma": None},
    {"kod": "DOGUB", "sembol": "DOGUB.IS", "ad": "DOGUSAN", "arindirma": None},
    {"kod": "DYOBY", "sembol": "DYOBY.IS", "ad": "DYO BOYA", "arindirma": None},
    {"kod": "EBEBK", "sembol": "EBEBK.IS", "ad": "EBEBEK MAGAZACILIK", "arindirma": None},
    {"kod": "EDATA", "sembol": "EDATA.IS", "ad": "E-DATA TEKNOLOJI", "arindirma": None},
    {"kod": "EDIP", "sembol": "EDIP.IS", "ad": "EDIP GAYRIMENKUL", "arindirma": None},
    {"kod": "EFOR", "sembol": "EFOR.IS", "ad": "EFOR YATIRIM", "arindirma": None},
    {"kod": "EGEPO", "sembol": "EGEPO.IS", "ad": "NASMED EGEPOL", "arindirma": None},
    {"kod": "EGGUB", "sembol": "EGGUB.IS", "ad": "EGE GUBRE", "arindirma": None},
    {"kod": "EGPRO", "sembol": "EGPRO.IS", "ad": "EGE PROFIL", "arindirma": None},
    {"kod": "EKGYO", "sembol": "EKGYO.IS", "ad": "EMLAK KONUT GMYO", "arindirma": None},
    {"kod": "EKSUN", "sembol": "EKSUN.IS", "ad": "EKSUN GIDA", "arindirma": None},
    {"kod": "ELITE", "sembol": "ELITE.IS", "ad": "ELITE NATUREL ORGANIK GIDA", "arindirma": None},
    {"kod": "EMPAE", "sembol": "EMPAE.IS", "ad": "EMPA ELEKTRONIK", "arindirma": None},
    {"kod": "ENJSA", "sembol": "ENJSA.IS", "ad": "ENERJISA ENERJI", "arindirma": None},
    {"kod": "EREGL", "sembol": "EREGL.IS", "ad": "EREGLI DEMIR CELIK", "arindirma": None},
    {"kod": "ESCOM", "sembol": "ESCOM.IS", "ad": "ESCORT TEKNOLOJI", "arindirma": None},
    {"kod": "EUPWR", "sembol": "EUPWR.IS", "ad": "EUROPOWER ENERJI", "arindirma": None},
    {"kod": "EYGYO", "sembol": "EYGYO.IS", "ad": "EYG GMYO", "arindirma": None},
    {"kod": "FADE", "sembol": "FADE.IS", "ad": "FADE GIDA", "arindirma": None},
    {"kod": "FONET", "sembol": "FONET.IS", "ad": "FONET BILGI TEKNOLOJILERI", "arindirma": None},
    {"kod": "FORMT", "sembol": "FORMT.IS", "ad": "FORMET METAL VE CAM", "arindirma": None},
    {"kod": "FORTE", "sembol": "FORTE.IS", "ad": "FORTE BILGI ILETISIM", "arindirma": None},
    {"kod": "FRMPL", "sembol": "FRMPL.IS", "ad": "FORMUL PLASTIK VE METAL", "arindirma": None},
    {"kod": "FZLGY", "sembol": "FZLGY.IS", "ad": "FUZUL GMYO", "arindirma": None},
    {"kod": "GEDZA", "sembol": "GEDZA.IS", "ad": "GEDIZ AMBALAJ", "arindirma": None},
    {"kod": "GENIL", "sembol": "GENIL.IS", "ad": "GEN ILAC", "arindirma": None},
    {"kod": "GENKM", "sembol": "GENKM.IS", "ad": "GENTAS KIMYA", "arindirma": None},
    {"kod": "GENTS", "sembol": "GENTS.IS", "ad": "GENTAS", "arindirma": None},
    {"kod": "GEREL", "sembol": "GEREL.IS", "ad": "GERSAN ELEKTRIK", "arindirma": None},
    {"kod": "GESAN", "sembol": "GESAN.IS", "ad": "GIRISIM ELEKTRIK SANAYI", "arindirma": None},
    {"kod": "GLRMK", "sembol": "GLRMK.IS", "ad": "GULERMAK AGIR SANAYI", "arindirma": None},
    {"kod": "GMTAS", "sembol": "GMTAS.IS", "ad": "GIMAT MAGAZACILIK", "arindirma": None},
    {"kod": "GOKNR", "sembol": "GOKNR.IS", "ad": "GOKNUR GIDA", "arindirma": None},
    {"kod": "GOLDA", "sembol": "GOLDA.IS", "ad": "GOLDA GIDA", "arindirma": None},
    {"kod": "GOLTS", "sembol": "GOLTS.IS", "ad": "GOLTAS CIMENTO", "arindirma": None},
    {"kod": "GOODY", "sembol": "GOODY.IS", "ad": "GOOD-YEAR", "arindirma": None},
    {"kod": "GRSEL", "sembol": "GRSEL.IS", "ad": "GUR-SEL TURIZM TASIMACILIK", "arindirma": None},
    {"kod": "GRTHO", "sembol": "GRTHO.IS", "ad": "GRAINTURK HOLDING", "arindirma": None},
    {"kod": "GUBRF", "sembol": "GUBRF.IS", "ad": "GUBRE FABRIK.", "arindirma": None},
    {"kod": "GUNDG", "sembol": "GUNDG.IS", "ad": "GUNDOGDU GIDA", "arindirma": None},
    {"kod": "HATSN", "sembol": "HATSN.IS", "ad": "HATSAN GEMI", "arindirma": None},
    {"kod": "HKTM", "sembol": "HKTM.IS", "ad": "HIDROPAR HAREKET KONTROL", "arindirma": None},
    {"kod": "HOROZ", "sembol": "HOROZ.IS", "ad": "HOROZ LOJISTIK", "arindirma": None},
    {"kod": "HRKET", "sembol": "HRKET.IS", "ad": "HAREKET PROJE TASIMACILIGI", "arindirma": None},
    {"kod": "IDGYO", "sembol": "IDGYO.IS", "ad": "IDEALIST GMYO", "arindirma": None},
    {"kod": "IHEVA", "sembol": "IHEVA.IS", "ad": "IHLAS EV ALETLERI", "arindirma": None},
    {"kod": "IHLAS", "sembol": "IHLAS.IS", "ad": "IHLAS HOLDING", "arindirma": None},
    {"kod": "IHLGM", "sembol": "IHLGM.IS", "ad": "IHLAS GAYRIMENKUL", "arindirma": None},
    {"kod": "IHYAY", "sembol": "IHYAY.IS", "ad": "IHLAS YAYIN HOLDING", "arindirma": None},
    {"kod": "IMASM", "sembol": "IMASM.IS", "ad": "IMAS MAKINA", "arindirma": None},
    {"kod": "INGRM", "sembol": "INGRM.IS", "ad": "INGRAM BILISIM", "arindirma": None},
    {"kod": "INTEM", "sembol": "INTEM.IS", "ad": "INTEMA", "arindirma": None},
    {"kod": "ISDMR", "sembol": "ISDMR.IS", "ad": "ISKENDERUN DEMIR CELIK", "arindirma": None},
    {"kod": "IZFAS", "sembol": "IZFAS.IS", "ad": "IZMIR FIRCA", "arindirma": None},
    {"kod": "IZINV", "sembol": "IZINV.IS", "ad": "IZ YATIRIM HOLDING", "arindirma": None},
    {"kod": "JANTS", "sembol": "JANTS.IS", "ad": "JANTSA JANT SANAYI", "arindirma": None},
    {"kod": "KARSN", "sembol": "KARSN.IS", "ad": "KARSAN OTOMOTIV", "arindirma": None},
    {"kod": "KATMR", "sembol": "KATMR.IS", "ad": "KATMERCILER EKIPMAN", "arindirma": None},
    {"kod": "KBORU", "sembol": "KBORU.IS", "ad": "KUZEY BORU", "arindirma": None},
    {"kod": "KCAER", "sembol": "KCAER.IS", "ad": "KOCAER CELIK", "arindirma": None},
    {"kod": "KIMMR", "sembol": "KIMMR.IS", "ad": "KIM MARKET-ERSAN ALISVERIS", "arindirma": None},
    {"kod": "KLSER", "sembol": "KLSER.IS", "ad": "KALESERAMIK", "arindirma": None},
    {"kod": "KLSYN", "sembol": "KLSYN.IS", "ad": "KOLEKSIYON MOBILYA", "arindirma": None},
    {"kod": "KMPUR", "sembol": "KMPUR.IS", "ad": "KIMTEKS POLIURETAN", "arindirma": None},
    {"kod": "KNFRT", "sembol": "KNFRT.IS", "ad": "KONFRUT TARIM", "arindirma": None},
    {"kod": "KOCMT", "sembol": "KOCMT.IS", "ad": "KOC METALURJI", "arindirma": None},
    {"kod": "KONKA", "sembol": "KONKA.IS", "ad": "KONYA KAGIT", "arindirma": None},
    {"kod": "KONYA", "sembol": "KONYA.IS", "ad": "KONYA CIMENTO", "arindirma": None},
    {"kod": "KOPOL", "sembol": "KOPOL.IS", "ad": "KOZA POLYESTER", "arindirma": None},
    {"kod": "KOTON", "sembol": "KOTON.IS", "ad": "KOTON MAGAZACILIK", "arindirma": None},
    {"kod": "KRDMA", "sembol": "KRDMA.IS", "ad": "KARDEMIR (A)", "arindirma": None},
    {"kod": "KRDMB", "sembol": "KRDMB.IS", "ad": "KARDEMIR (B)", "arindirma": None},
    {"kod": "KRDMD", "sembol": "KRDMD.IS", "ad": "KARDEMIR (D)", "arindirma": None},
    {"kod": "KRGYO", "sembol": "KRGYO.IS", "ad": "KORFEZ GMYO", "arindirma": None},
    {"kod": "KRONT", "sembol": "KRONT.IS", "ad": "KRON TEKNOLOJI", "arindirma": None},
    {"kod": "KRPLS", "sembol": "KRPLS.IS", "ad": "KOROPLAST TEMIZLIK AMBALAJ", "arindirma": None},
    {"kod": "KRSTL", "sembol": "KRSTL.IS", "ad": "KRISTAL KOLA", "arindirma": None},
    {"kod": "KRVGD", "sembol": "KRVGD.IS", "ad": "KERVAN GIDA", "arindirma": None},
    {"kod": "KTLEV", "sembol": "KTLEV.IS", "ad": "KATILIMEVIM TAS. FIN.", "arindirma": None},
    {"kod": "KUTPO", "sembol": "KUTPO.IS", "ad": "KUTAHYA PORSELEN", "arindirma": None},
    {"kod": "KZBGY", "sembol": "KZBGY.IS", "ad": "KIZILBUK GYO", "arindirma": None},
    {"kod": "LKMNH", "sembol": "LKMNH.IS", "ad": "LOKMAN HEKIM SAGLIK", "arindirma": None},
    {"kod": "LMKDC", "sembol": "LMKDC.IS", "ad": "LIMAK DOGU ANADOLU", "arindirma": None},
    {"kod": "LOGO", "sembol": "LOGO.IS", "ad": "LOGO YAZILIM", "arindirma": None},
    {"kod": "LXGYO", "sembol": "LXGYO.IS", "ad": "LUXERA GMYO", "arindirma": None},
    {"kod": "MAGEN", "sembol": "MAGEN.IS", "ad": "MARGUN ENERJI", "arindirma": None},
    {"kod": "MAKIM", "sembol": "MAKIM.IS", "ad": "MAKIM MAKINE", "arindirma": None},
    {"kod": "MARBL", "sembol": "MARBL.IS", "ad": "TUREKS TURUNC MADENCILIK", "arindirma": None},
    {"kod": "MAVI", "sembol": "MAVI.IS", "ad": "MAVI GIYIM", "arindirma": None},
    {"kod": "MCARD", "sembol": "MCARD.IS", "ad": "METROPAL KURUMSAL HIZMETLER", "arindirma": None},
    {"kod": "MEDTR", "sembol": "MEDTR.IS", "ad": "MEDITERA TIBBI MALZEME", "arindirma": None},
    {"kod": "MEGMT", "sembol": "MEGMT.IS", "ad": "MEGA METAL", "arindirma": None},
    {"kod": "MEKAG", "sembol": "MEKAG.IS", "ad": "MEKA GLOBAL MAKINE", "arindirma": None},
    {"kod": "MERCN", "sembol": "MERCN.IS", "ad": "MERCAN KIMYA", "arindirma": None},
    {"kod": "MERKO", "sembol": "MERKO.IS", "ad": "MERKO GIDA", "arindirma": None},
    {"kod": "MEYSU", "sembol": "MEYSU.IS", "ad": "MEYSU GIDA", "arindirma": None},
    {"kod": "MNDTR", "sembol": "MNDTR.IS", "ad": "MONDI TURKEY", "arindirma": None},
    {"kod": "MOBTL", "sembol": "MOBTL.IS", "ad": "MOBILTEL ILETISIM", "arindirma": None},
    {"kod": "MOPAS", "sembol": "MOPAS.IS", "ad": "MOPAS MARKETCILIK", "arindirma": None},
    {"kod": "MPARK", "sembol": "MPARK.IS", "ad": "MLP SAGLIK", "arindirma": None},
    {"kod": "NETAS", "sembol": "NETAS.IS", "ad": "NETAS TELEKOM.", "arindirma": None},
    {"kod": "NETCD", "sembol": "NETCD.IS", "ad": "NETCAD YAZILIM", "arindirma": None},
    {"kod": "NTGAZ", "sembol": "NTGAZ.IS", "ad": "NATURELGAZ", "arindirma": None},
    {"kod": "OBAMS", "sembol": "OBAMS.IS", "ad": "OBA MAKARNACILIK", "arindirma": None},
    {"kod": "OBASE", "sembol": "OBASE.IS", "ad": "OBASE BILGISAYAR", "arindirma": None},
    {"kod": "ONCSM", "sembol": "ONCSM.IS", "ad": "ONCOSEM ONKOLOJIK SISTEMLER", "arindirma": None},
    {"kod": "ORGE", "sembol": "ORGE.IS", "ad": "ORGE ENERJI ELEKTRIK", "arindirma": None},
    {"kod": "OSTIM", "sembol": "OSTIM.IS", "ad": "OSTIM ENDUSTRIYEL YAT", "arindirma": None},
    {"kod": "OZATD", "sembol": "OZATD.IS", "ad": "OZATA DENIZCILIK", "arindirma": None},
    {"kod": "OZGYO", "sembol": "OZGYO.IS", "ad": "OZDERICI GMYO", "arindirma": None},
    {"kod": "OZRDN", "sembol": "OZRDN.IS", "ad": "OZERDEN AMBALAJ", "arindirma": None},
    {"kod": "OZYSR", "sembol": "OZYSR.IS", "ad": "OZYASAR TEL", "arindirma": None},
    {"kod": "PAGYO", "sembol": "PAGYO.IS", "ad": "PANORA GMYO", "arindirma": None},
    {"kod": "PARSN", "sembol": "PARSN.IS", "ad": "PARSAN", "arindirma": None},
    {"kod": "PASEU", "sembol": "PASEU.IS", "ad": "PASIFIK EURASIA LOJISTIK", "arindirma": None},
    {"kod": "PENGD", "sembol": "PENGD.IS", "ad": "PENGUEN GIDA", "arindirma": None},
    {"kod": "PENTA", "sembol": "PENTA.IS", "ad": "PENTA TEKNOLOJI URUNLERI DAGITIM", "arindirma": None},
    {"kod": "PETKM", "sembol": "PETKM.IS", "ad": "PETKIM", "arindirma": None},
    {"kod": "PKART", "sembol": "PKART.IS", "ad": "PLASTIKKART", "arindirma": None},
    {"kod": "PLTUR", "sembol": "PLTUR.IS", "ad": "PLATFORM TURIZM", "arindirma": None},
    {"kod": "PNSUT", "sembol": "PNSUT.IS", "ad": "PINAR SUT", "arindirma": None},
    {"kod": "POLHO", "sembol": "POLHO.IS", "ad": "POLISAN HOLDING", "arindirma": None},
    {"kod": "PRKME", "sembol": "PRKME.IS", "ad": "PARK ELEK.MADENCILIK", "arindirma": None},
    {"kod": "QUAGR", "sembol": "QUAGR.IS", "ad": "QUA GRANITE HAYAL YAPI", "arindirma": None},
    {"kod": "RALYH", "sembol": "RALYH.IS", "ad": "RAL YATIRIM HOLDING", "arindirma": None},
    {"kod": "RGYAS", "sembol": "RGYAS.IS", "ad": "RONESANS GAYRIMENKUL YAT.", "arindirma": None},
    {"kod": "RNPOL", "sembol": "RNPOL.IS", "ad": "RAINBOW POLIKARBONAT", "arindirma": None},
    {"kod": "RODRG", "sembol": "RODRG.IS", "ad": "RODRIGO TEKSTIL", "arindirma": None},
    {"kod": "RUBNS", "sembol": "RUBNS.IS", "ad": "RUBENIS TEKSTIL", "arindirma": None},
    {"kod": "SAFKR", "sembol": "SAFKR.IS", "ad": "SAFKAR EGE SOGUTMACILIK", "arindirma": None},
    {"kod": "SAMAT", "sembol": "SAMAT.IS", "ad": "SARAY MATBAACILIK", "arindirma": None},
    {"kod": "SANEL", "sembol": "SANEL.IS", "ad": "SANEL MUHENDISLIK", "arindirma": None},
    {"kod": "SANKO", "sembol": "SANKO.IS", "ad": "SANKO PAZARLAMA", "arindirma": None},
    {"kod": "SARKY", "sembol": "SARKY.IS", "ad": "SARKUYSAN", "arindirma": None},
    {"kod": "SAYAS", "sembol": "SAYAS.IS", "ad": "SAY YENILENEBILIR ENERJI", "arindirma": None},
    {"kod": "SDTTR", "sembol": "SDTTR.IS", "ad": "SDT UZAY VE SAVUNMA", "arindirma": None},
    {"kod": "SEKUR", "sembol": "SEKUR.IS", "ad": "SEKURO PLASTIK", "arindirma": None},
    {"kod": "SELEC", "sembol": "SELEC.IS", "ad": "SELCUK ECZA DEPOSU", "arindirma": None},
    {"kod": "SELVA", "sembol": "SELVA.IS", "ad": "SELVA GIDA", "arindirma": None},
    {"kod": "SILVR", "sembol": "SILVR.IS", "ad": "SILVERLINE ENDUSTRI", "arindirma": None},
    {"kod": "SMART", "sembol": "SMART.IS", "ad": "SMARTIKS YAZILIM", "arindirma": None},
    {"kod": "SNGYO", "sembol": "SNGYO.IS", "ad": "SINPAS GMYO", "arindirma": None},
    {"kod": "SNICA", "sembol": "SNICA.IS", "ad": "SANICA ISI SANAYI", "arindirma": None},
    {"kod": "SOHOE", "sembol": "SOHOE.IS", "ad": "SOHO GIYIM VE ENERJI", "arindirma": None},
    {"kod": "SOKE", "sembol": "SOKE.IS", "ad": "SOKE DEGIRMENCILIK", "arindirma": None},
    {"kod": "SRVGY", "sembol": "SRVGY.IS", "ad": "SERVET GMYO", "arindirma": None},
    {"kod": "SSAAT", "sembol": "SSAAT.IS", "ad": "SAAT VE SAAT SANAYI", "arindirma": None},
    {"kod": "SUNTK", "sembol": "SUNTK.IS", "ad": "SUN TEKSTIL", "arindirma": None},
    {"kod": "SURGY", "sembol": "SURGY.IS", "ad": "SUR TATIL EVLERI GMYO", "arindirma": None},
    {"kod": "SUWEN", "sembol": "SUWEN.IS", "ad": "SUWEN TEKSTIL", "arindirma": None},
    {"kod": "TARKM", "sembol": "TARKM.IS", "ad": "TARKIM BITKI KORUMA", "arindirma": None},
    {"kod": "TEZOL", "sembol": "TEZOL.IS", "ad": "EUROPAP TEZOL KAGIT", "arindirma": None},
    {"kod": "TKFEN", "sembol": "TKFEN.IS", "ad": "TEKFEN HOLDING", "arindirma": None},
    {"kod": "TKNSA", "sembol": "TKNSA.IS", "ad": "TEKNOSA IC VE DIS TICARET", "arindirma": None},
    {"kod": "TMPOL", "sembol": "TMPOL.IS", "ad": "TEMAPOL POLIMER PLASTIK", "arindirma": None},
    {"kod": "TUCLK", "sembol": "TUCLK.IS", "ad": "TUGCELIK", "arindirma": None},
    {"kod": "TUKAS", "sembol": "TUKAS.IS", "ad": "TUKAS", "arindirma": None},
    {"kod": "TUPRS", "sembol": "TUPRS.IS", "ad": "TUPRAS", "arindirma": None},
    {"kod": "TUREX", "sembol": "TUREX.IS", "ad": "TUREKS TURIZM TASIMACILIK", "arindirma": None},
    {"kod": "TURGG", "sembol": "TURGG.IS", "ad": "TURKER PROJE GAYRIMENKUL", "arindirma": None},
    {"kod": "UCAYM", "sembol": "UCAYM.IS", "ad": "UCAY MUHENDISLIK", "arindirma": None},
    {"kod": "UFUK", "sembol": "UFUK.IS", "ad": "UFUK YATIRIM", "arindirma": None},
    {"kod": "ULUSE", "sembol": "ULUSE.IS", "ad": "ULUSOY ELEKTRIK", "arindirma": None},
    {"kod": "USAK", "sembol": "USAK.IS", "ad": "USAK SERAMIK", "arindirma": None},
    {"kod": "VAKKO", "sembol": "VAKKO.IS", "ad": "VAKKO TEKSTIL", "arindirma": None},
    {"kod": "VANGD", "sembol": "VANGD.IS", "ad": "VANET GIDA", "arindirma": None},
    {"kod": "YATAS", "sembol": "YATAS.IS", "ad": "YATAS", "arindirma": None},
    {"kod": "YEOTK", "sembol": "YEOTK.IS", "ad": "YEO TEKNOLOJI ENERJI", "arindirma": None},
    {"kod": "YIGIT", "sembol": "YIGIT.IS", "ad": "YIGIT AKU", "arindirma": None},
    {"kod": "YKSLN", "sembol": "YKSLN.IS", "ad": "YUKSELEN CELIK", "arindirma": None},
    {"kod": "YUNSA", "sembol": "YUNSA.IS", "ad": "YUNSA", "arindirma": None},
    {"kod": "ZEDUR", "sembol": "ZEDUR.IS", "ad": "ZEDUR ENERJI", "arindirma": None},
    {"kod": "ZERGY", "sembol": "ZERGY.IS", "ad": "ZERAY GMYO", "arindirma": None},
]

KATILIM_100 = [
    {"kod": "AKFYE", "sembol": "AKFYE.IS", "ad": "AKFEN YEN. ENERJI", "arindirma": None},
    {"kod": "ALBRK", "sembol": "ALBRK.IS", "ad": "ALBARAKA TURK", "arindirma": None},
    {"kod": "ALFAS", "sembol": "ALFAS.IS", "ad": "ALFA SOLAR ENERJI", "arindirma": None},
    {"kod": "ALKLC", "sembol": "ALKLC.IS", "ad": "ALTINKILIC GIDA VE SUT", "arindirma": None},
    {"kod": "ALTNY", "sembol": "ALTNY.IS", "ad": "ALTINAY SAVUNMA", "arindirma": None},
    {"kod": "ALVES", "sembol": "ALVES.IS", "ad": "ALVES KABLO", "arindirma": None},
    {"kod": "ARDYZ", "sembol": "ARDYZ.IS", "ad": "ARD BILISIM TEKNOLOJILERI", "arindirma": None},
    {"kod": "ASELS", "sembol": "ASELS.IS", "ad": "ASELSAN", "arindirma": None},
    {"kod": "ATATP", "sembol": "ATATP.IS", "ad": "ATP YAZILIM", "arindirma": None},
    {"kod": "BEGYO", "sembol": "BEGYO.IS", "ad": "BATI EGE GMYO", "arindirma": None},
    {"kod": "BERA", "sembol": "BERA.IS", "ad": "BERA HOLDING", "arindirma": None},
    {"kod": "BIENY", "sembol": "BIENY.IS", "ad": "BIEN YAPI URUNLERI", "arindirma": None},
    {"kod": "BIMAS", "sembol": "BIMAS.IS", "ad": "BIM MAGAZALAR", "arindirma": None},
    {"kod": "BINBN", "sembol": "BINBN.IS", "ad": "BIN ULASIM TEKNOLOJILERI", "arindirma": None},
    {"kod": "BINHO", "sembol": "BINHO.IS", "ad": "1000 YATIRIMLAR HOL.", "arindirma": None},
    {"kod": "BMSTL", "sembol": "BMSTL.IS", "ad": "BMS BIRLESIK METAL", "arindirma": None},
    {"kod": "BSOKE", "sembol": "BSOKE.IS", "ad": "BATICIM CIMENTO", "arindirma": None},
    {"kod": "CANTE", "sembol": "CANTE.IS", "ad": "CAN2 TERMIK", "arindirma": None},
    {"kod": "CEMTS", "sembol": "CEMTS.IS", "ad": "CEMTAS", "arindirma": None},
    {"kod": "CEMZY", "sembol": "CEMZY.IS", "ad": "CEM ZEYTIN", "arindirma": None},
    {"kod": "CIMSA", "sembol": "CIMSA.IS", "ad": "CIMSA", "arindirma": None},
    {"kod": "CVKMD", "sembol": "CVKMD.IS", "ad": "CVK MADEN", "arindirma": None},
    {"kod": "CWENE", "sembol": "CWENE.IS", "ad": "CW ENERJI", "arindirma": None},
    {"kod": "DAPGM", "sembol": "DAPGM.IS", "ad": "DAP GAYRIMENKUL", "arindirma": None},
    {"kod": "DCTTR", "sembol": "DCTTR.IS", "ad": "DCT TRADING DIS TICARET", "arindirma": None},
    {"kod": "DOFRB", "sembol": "DOFRB.IS", "ad": "DOF ROBOTIK", "arindirma": None},
    {"kod": "EFOR", "sembol": "EFOR.IS", "ad": "EFOR YATIRIM", "arindirma": None},
    {"kod": "EGGUB", "sembol": "EGGUB.IS", "ad": "EGE GUBRE", "arindirma": None},
    {"kod": "EKGYO", "sembol": "EKGYO.IS", "ad": "EMLAK KONUT GMYO", "arindirma": None},
    {"kod": "ENJSA", "sembol": "ENJSA.IS", "ad": "ENERJISA ENERJI", "arindirma": None},
    {"kod": "EREGL", "sembol": "EREGL.IS", "ad": "EREGLI DEMIR CELIK", "arindirma": None},
    {"kod": "EUPWR", "sembol": "EUPWR.IS", "ad": "EUROPOWER ENERJI", "arindirma": None},
    {"kod": "FONET", "sembol": "FONET.IS", "ad": "FONET BILGI TEKNOLOJILERI", "arindirma": None},
    {"kod": "FORMT", "sembol": "FORMT.IS", "ad": "FORMET METAL VE CAM", "arindirma": None},
    {"kod": "FZLGY", "sembol": "FZLGY.IS", "ad": "FUZUL GMYO", "arindirma": None},
    {"kod": "GENIL", "sembol": "GENIL.IS", "ad": "GEN ILAC", "arindirma": None},
    {"kod": "GENTS", "sembol": "GENTS.IS", "ad": "GENTAS", "arindirma": None},
    {"kod": "GEREL", "sembol": "GEREL.IS", "ad": "GERSAN ELEKTRIK", "arindirma": None},
    {"kod": "GESAN", "sembol": "GESAN.IS", "ad": "GIRISIM ELEKTRIK SANAYI", "arindirma": None},
    {"kod": "GLRMK", "sembol": "GLRMK.IS", "ad": "GULERMAK AGIR SANAYI", "arindirma": None},
    {"kod": "GOKNR", "sembol": "GOKNR.IS", "ad": "GOKNUR GIDA", "arindirma": None},
    {"kod": "GRSEL", "sembol": "GRSEL.IS", "ad": "GUR-SEL TURIZM TASIMACILIK", "arindirma": None},
    {"kod": "GRTHO", "sembol": "GRTHO.IS", "ad": "GRAINTURK HOLDING", "arindirma": None},
    {"kod": "GUBRF", "sembol": "GUBRF.IS", "ad": "GUBRE FABRIK.", "arindirma": None},
    {"kod": "GUNDG", "sembol": "GUNDG.IS", "ad": "GUNDOGDU GIDA", "arindirma": None},
    {"kod": "HRKET", "sembol": "HRKET.IS", "ad": "HAREKET PROJE TASIMACILIGI", "arindirma": None},
    {"kod": "IHLAS", "sembol": "IHLAS.IS", "ad": "IHLAS HOLDING", "arindirma": None},
    {"kod": "IHLGM", "sembol": "IHLGM.IS", "ad": "IHLAS GAYRIMENKUL", "arindirma": None},
    {"kod": "IMASM", "sembol": "IMASM.IS", "ad": "IMAS MAKINA", "arindirma": None},
    {"kod": "ISDMR", "sembol": "ISDMR.IS", "ad": "ISKENDERUN DEMIR CELIK", "arindirma": None},
    {"kod": "IZFAS", "sembol": "IZFAS.IS", "ad": "IZMIR FIRCA", "arindirma": None},
    {"kod": "JANTS", "sembol": "JANTS.IS", "ad": "JANTSA JANT SANAYI", "arindirma": None},
    {"kod": "KARSN", "sembol": "KARSN.IS", "ad": "KARSAN OTOMOTIV", "arindirma": None},
    {"kod": "KATMR", "sembol": "KATMR.IS", "ad": "KATMERCILER EKIPMAN", "arindirma": None},
    {"kod": "KBORU", "sembol": "KBORU.IS", "ad": "KUZEY BORU", "arindirma": None},
    {"kod": "KCAER", "sembol": "KCAER.IS", "ad": "KOCAER CELIK", "arindirma": None},
    {"kod": "KOPOL", "sembol": "KOPOL.IS", "ad": "KOZA POLYESTER", "arindirma": None},
    {"kod": "KRDMD", "sembol": "KRDMD.IS", "ad": "KARDEMIR (D)", "arindirma": None},
    {"kod": "KTLEV", "sembol": "KTLEV.IS", "ad": "KATILIMEVIM TAS. FIN.", "arindirma": None},
    {"kod": "KZBGY", "sembol": "KZBGY.IS", "ad": "KIZILBUK GYO", "arindirma": None},
    {"kod": "LMKDC", "sembol": "LMKDC.IS", "ad": "LIMAK DOGU ANADOLU", "arindirma": None},
    {"kod": "LOGO", "sembol": "LOGO.IS", "ad": "LOGO YAZILIM", "arindirma": None},
    {"kod": "MAGEN", "sembol": "MAGEN.IS", "ad": "MARGUN ENERJI", "arindirma": None},
    {"kod": "MAVI", "sembol": "MAVI.IS", "ad": "MAVI GIYIM", "arindirma": None},
    {"kod": "MEGMT", "sembol": "MEGMT.IS", "ad": "MEGA METAL", "arindirma": None},
    {"kod": "MERCN", "sembol": "MERCN.IS", "ad": "MERCAN KIMYA", "arindirma": None},
    {"kod": "MEYSU", "sembol": "MEYSU.IS", "ad": "MEYSU GIDA", "arindirma": None},
    {"kod": "MOPAS", "sembol": "MOPAS.IS", "ad": "MOPAS MARKETCILIK", "arindirma": None},
    {"kod": "MPARK", "sembol": "MPARK.IS", "ad": "MLP SAGLIK", "arindirma": None},
    {"kod": "NETCD", "sembol": "NETCD.IS", "ad": "NETCAD YAZILIM", "arindirma": None},
    {"kod": "NTGAZ", "sembol": "NTGAZ.IS", "ad": "NATURELGAZ", "arindirma": None},
    {"kod": "OBAMS", "sembol": "OBAMS.IS", "ad": "OBA MAKARNACILIK", "arindirma": None},
    {"kod": "ORGE", "sembol": "ORGE.IS", "ad": "ORGE ENERJI ELEKTRIK", "arindirma": None},
    {"kod": "OZATD", "sembol": "OZATD.IS", "ad": "OZATA DENIZCILIK", "arindirma": None},
    {"kod": "PASEU", "sembol": "PASEU.IS", "ad": "PASIFIK EURASIA LOJISTIK", "arindirma": None},
    {"kod": "PETKM", "sembol": "PETKM.IS", "ad": "PETKIM", "arindirma": None},
    {"kod": "POLHO", "sembol": "POLHO.IS", "ad": "POLISAN HOLDING", "arindirma": None},
    {"kod": "QUAGR", "sembol": "QUAGR.IS", "ad": "QUA GRANITE HAYAL YAPI", "arindirma": None},
    {"kod": "RALYH", "sembol": "RALYH.IS", "ad": "RAL YATIRIM HOLDING", "arindirma": None},
    {"kod": "RGYAS", "sembol": "RGYAS.IS", "ad": "RONESANS GAYRIMENKUL YAT.", "arindirma": None},
    {"kod": "SAFKR", "sembol": "SAFKR.IS", "ad": "SAFKAR EGE SOGUTMACILIK", "arindirma": None},
    {"kod": "SARKY", "sembol": "SARKY.IS", "ad": "SARKUYSAN", "arindirma": None},
    {"kod": "SAYAS", "sembol": "SAYAS.IS", "ad": "SAY YENILENEBILIR ENERJI", "arindirma": None},
    {"kod": "SDTTR", "sembol": "SDTTR.IS", "ad": "SDT UZAY VE SAVUNMA", "arindirma": None},
    {"kod": "SELEC", "sembol": "SELEC.IS", "ad": "SELCUK ECZA DEPOSU", "arindirma": None},
    {"kod": "SNGYO", "sembol": "SNGYO.IS", "ad": "SINPAS GMYO", "arindirma": None},
    {"kod": "SRVGY", "sembol": "SRVGY.IS", "ad": "SERVET GMYO", "arindirma": None},
    {"kod": "SUNTK", "sembol": "SUNTK.IS", "ad": "SUN TEKSTIL", "arindirma": None},
    {"kod": "SURGY", "sembol": "SURGY.IS", "ad": "SUR TATIL EVLERI GMYO", "arindirma": None},
    {"kod": "TARKM", "sembol": "TARKM.IS", "ad": "TARKIM BITKI KORUMA", "arindirma": None},
    {"kod": "TEZOL", "sembol": "TEZOL.IS", "ad": "EUROPAP TEZOL KAGIT", "arindirma": None},
    {"kod": "TKFEN", "sembol": "TKFEN.IS", "ad": "TEKFEN HOLDING", "arindirma": None},
    {"kod": "TKNSA", "sembol": "TKNSA.IS", "ad": "TEKNOSA IC VE DIS TICARET", "arindirma": None},
    {"kod": "TUKAS", "sembol": "TUKAS.IS", "ad": "TUKAS", "arindirma": None},
    {"kod": "TUPRS", "sembol": "TUPRS.IS", "ad": "TUPRAS", "arindirma": None},
    {"kod": "TUREX", "sembol": "TUREX.IS", "ad": "TUREKS TURIZM TASIMACILIK", "arindirma": None},
    {"kod": "USAK", "sembol": "USAK.IS", "ad": "USAK SERAMIK", "arindirma": None},
    {"kod": "YEOTK", "sembol": "YEOTK.IS", "ad": "YEO TEKNOLOJI ENERJI", "arindirma": None},
    {"kod": "YIGIT", "sembol": "YIGIT.IS", "ad": "YIGIT AKU", "arindirma": None},
    {"kod": "ZERGY", "sembol": "ZERGY.IS", "ad": "ZERAY GMYO", "arindirma": None},
]

KATILIM_50 = [
    {"kod": "ALKLC", "sembol": "ALKLC.IS", "ad": "ALTINKILIC GIDA VE SUT", "arindirma": None},
    {"kod": "ALTNY", "sembol": "ALTNY.IS", "ad": "ALTINAY SAVUNMA", "arindirma": None},
    {"kod": "ASELS", "sembol": "ASELS.IS", "ad": "ASELSAN", "arindirma": None},
    {"kod": "BERA", "sembol": "BERA.IS", "ad": "BERA HOLDING", "arindirma": None},
    {"kod": "BIMAS", "sembol": "BIMAS.IS", "ad": "BIM MAGAZALAR", "arindirma": None},
    {"kod": "BINHO", "sembol": "BINHO.IS", "ad": "1000 YATIRIMLAR HOL.", "arindirma": None},
    {"kod": "BMSTL", "sembol": "BMSTL.IS", "ad": "BMS BIRLESIK METAL", "arindirma": None},
    {"kod": "BSOKE", "sembol": "BSOKE.IS", "ad": "BATICIM CIMENTO", "arindirma": None},
    {"kod": "CANTE", "sembol": "CANTE.IS", "ad": "CAN2 TERMIK", "arindirma": None},
    {"kod": "CIMSA", "sembol": "CIMSA.IS", "ad": "CIMSA", "arindirma": None},
    {"kod": "CVKMD", "sembol": "CVKMD.IS", "ad": "CVK MADEN", "arindirma": None},
    {"kod": "CWENE", "sembol": "CWENE.IS", "ad": "CW ENERJI", "arindirma": None},
    {"kod": "DAPGM", "sembol": "DAPGM.IS", "ad": "DAP GAYRIMENKUL", "arindirma": None},
    {"kod": "DOFRB", "sembol": "DOFRB.IS", "ad": "DOF ROBOTIK", "arindirma": None},
    {"kod": "EFOR", "sembol": "EFOR.IS", "ad": "EFOR YATIRIM", "arindirma": None},
    {"kod": "EKGYO", "sembol": "EKGYO.IS", "ad": "EMLAK KONUT GMYO", "arindirma": None},
    {"kod": "ENJSA", "sembol": "ENJSA.IS", "ad": "ENERJISA ENERJI", "arindirma": None},
    {"kod": "EREGL", "sembol": "EREGL.IS", "ad": "EREGLI DEMIR CELIK", "arindirma": None},
    {"kod": "EUPWR", "sembol": "EUPWR.IS", "ad": "EUROPOWER ENERJI", "arindirma": None},
    {"kod": "FORMT", "sembol": "FORMT.IS", "ad": "FORMET METAL VE CAM", "arindirma": None},
    {"kod": "GENIL", "sembol": "GENIL.IS", "ad": "GEN ILAC", "arindirma": None},
    {"kod": "GESAN", "sembol": "GESAN.IS", "ad": "GIRISIM ELEKTRIK SANAYI", "arindirma": None},
    {"kod": "GLRMK", "sembol": "GLRMK.IS", "ad": "GULERMAK AGIR SANAYI", "arindirma": None},
    {"kod": "GRSEL", "sembol": "GRSEL.IS", "ad": "GUR-SEL TURIZM TASIMACILIK", "arindirma": None},
    {"kod": "GRTHO", "sembol": "GRTHO.IS", "ad": "GRAINTURK HOLDING", "arindirma": None},
    {"kod": "GUBRF", "sembol": "GUBRF.IS", "ad": "GUBRE FABRIK.", "arindirma": None},
    {"kod": "IHLAS", "sembol": "IHLAS.IS", "ad": "IHLAS HOLDING", "arindirma": None},
    {"kod": "IZFAS", "sembol": "IZFAS.IS", "ad": "IZMIR FIRCA", "arindirma": None},
    {"kod": "KARSN", "sembol": "KARSN.IS", "ad": "KARSAN OTOMOTIV", "arindirma": None},
    {"kod": "KATMR", "sembol": "KATMR.IS", "ad": "KATMERCILER EKIPMAN", "arindirma": None},
    {"kod": "KCAER", "sembol": "KCAER.IS", "ad": "KOCAER CELIK", "arindirma": None},
    {"kod": "KRDMD", "sembol": "KRDMD.IS", "ad": "KARDEMIR (D)", "arindirma": None},
    {"kod": "KTLEV", "sembol": "KTLEV.IS", "ad": "KATILIMEVIM TAS. FIN.", "arindirma": None},
    {"kod": "KZBGY", "sembol": "KZBGY.IS", "ad": "KIZILBUK GYO", "arindirma": None},
    {"kod": "MAGEN", "sembol": "MAGEN.IS", "ad": "MARGUN ENERJI", "arindirma": None},
    {"kod": "MAVI", "sembol": "MAVI.IS", "ad": "MAVI GIYIM", "arindirma": None},
    {"kod": "MPARK", "sembol": "MPARK.IS", "ad": "MLP SAGLIK", "arindirma": None},
    {"kod": "NETCD", "sembol": "NETCD.IS", "ad": "NETCAD YAZILIM", "arindirma": None},
    {"kod": "OBAMS", "sembol": "OBAMS.IS", "ad": "OBA MAKARNACILIK", "arindirma": None},
    {"kod": "PASEU", "sembol": "PASEU.IS", "ad": "PASIFIK EURASIA LOJISTIK", "arindirma": None},
    {"kod": "PETKM", "sembol": "PETKM.IS", "ad": "PETKIM", "arindirma": None},
    {"kod": "QUAGR", "sembol": "QUAGR.IS", "ad": "QUA GRANITE HAYAL YAPI", "arindirma": None},
    {"kod": "RALYH", "sembol": "RALYH.IS", "ad": "RAL YATIRIM HOLDING", "arindirma": None},
    {"kod": "SARKY", "sembol": "SARKY.IS", "ad": "SARKUYSAN", "arindirma": None},
    {"kod": "TKFEN", "sembol": "TKFEN.IS", "ad": "TEKFEN HOLDING", "arindirma": None},
    {"kod": "TUKAS", "sembol": "TUKAS.IS", "ad": "TUKAS", "arindirma": None},
    {"kod": "TUPRS", "sembol": "TUPRS.IS", "ad": "TUPRAS", "arindirma": None},
    {"kod": "TUREX", "sembol": "TUREX.IS", "ad": "TUREKS TURIZM TASIMACILIK", "arindirma": None},
    {"kod": "USAK", "sembol": "USAK.IS", "ad": "USAK SERAMIK", "arindirma": None},
    {"kod": "YEOTK", "sembol": "YEOTK.IS", "ad": "YEO TEKNOLOJI ENERJI", "arindirma": None},
]

KATILIM_30 = [
    {"kod": "ALKLC", "sembol": "ALKLC.IS", "ad": "ALTINKILIC GIDA VE SUT", "arindirma": None},
    {"kod": "ALTNY", "sembol": "ALTNY.IS", "ad": "ALTINAY SAVUNMA", "arindirma": None},
    {"kod": "ASELS", "sembol": "ASELS.IS", "ad": "ASELSAN", "arindirma": None},
    {"kod": "BIMAS", "sembol": "BIMAS.IS", "ad": "BIM MAGAZALAR", "arindirma": None},
    {"kod": "BSOKE", "sembol": "BSOKE.IS", "ad": "BATICIM CIMENTO", "arindirma": None},
    {"kod": "CANTE", "sembol": "CANTE.IS", "ad": "CAN2 TERMIK", "arindirma": None},
    {"kod": "CIMSA", "sembol": "CIMSA.IS", "ad": "CIMSA", "arindirma": None},
    {"kod": "CVKMD", "sembol": "CVKMD.IS", "ad": "CVK MADEN", "arindirma": None},
    {"kod": "CWENE", "sembol": "CWENE.IS", "ad": "CW ENERJI", "arindirma": None},
    {"kod": "DAPGM", "sembol": "DAPGM.IS", "ad": "DAP GAYRIMENKUL", "arindirma": None},
    {"kod": "EFOR", "sembol": "EFOR.IS", "ad": "EFOR YATIRIM", "arindirma": None},
    {"kod": "EKGYO", "sembol": "EKGYO.IS", "ad": "EMLAK KONUT GMYO", "arindirma": None},
    {"kod": "EREGL", "sembol": "EREGL.IS", "ad": "EREGLI DEMIR CELIK", "arindirma": None},
    {"kod": "EUPWR", "sembol": "EUPWR.IS", "ad": "EUROPOWER ENERJI", "arindirma": None},
    {"kod": "GENIL", "sembol": "GENIL.IS", "ad": "GEN ILAC", "arindirma": None},
    {"kod": "GLRMK", "sembol": "GLRMK.IS", "ad": "GULERMAK AGIR SANAYI", "arindirma": None},
    {"kod": "GUBRF", "sembol": "GUBRF.IS", "ad": "GUBRE FABRIK.", "arindirma": None},
    {"kod": "KRDMD", "sembol": "KRDMD.IS", "ad": "KARDEMIR (D)", "arindirma": None},
    {"kod": "KTLEV", "sembol": "KTLEV.IS", "ad": "KATILIMEVIM TAS. FIN.", "arindirma": None},
    {"kod": "MAVI", "sembol": "MAVI.IS", "ad": "MAVI GIYIM", "arindirma": None},
    {"kod": "OBAMS", "sembol": "OBAMS.IS", "ad": "OBA MAKARNACILIK", "arindirma": None},
    {"kod": "PASEU", "sembol": "PASEU.IS", "ad": "PASIFIK EURASIA LOJISTIK", "arindirma": None},
    {"kod": "PETKM", "sembol": "PETKM.IS", "ad": "PETKIM", "arindirma": None},
    {"kod": "QUAGR", "sembol": "QUAGR.IS", "ad": "QUA GRANITE HAYAL YAPI", "arindirma": None},
    {"kod": "RALYH", "sembol": "RALYH.IS", "ad": "RAL YATIRIM HOLDING", "arindirma": None},
    {"kod": "TKFEN", "sembol": "TKFEN.IS", "ad": "TEKFEN HOLDING", "arindirma": None},
    {"kod": "TUKAS", "sembol": "TUKAS.IS", "ad": "TUKAS", "arindirma": None},
    {"kod": "TUPRS", "sembol": "TUPRS.IS", "ad": "TUPRAS", "arindirma": None},
    {"kod": "TUREX", "sembol": "TUREX.IS", "ad": "TUREKS TURIZM TASIMACILIK", "arindirma": None},
    {"kod": "YEOTK", "sembol": "YEOTK.IS", "ad": "YEO TEKNOLOJI ENERJI", "arindirma": None},
]

BIST_UNIVERSES = {
    "Katılım Tüm": KATILIM_TUM,
    "Katılım 100": KATILIM_100,
    "Katılım 50": KATILIM_50,
    "Katılım 30": KATILIM_30,
}

CRYPTO_UNIVERSE = {'BTC': {'pair': 'BTC/USDT', 'name': 'Bitcoin', 'group': 'core'},
 'ETH': {'pair': 'ETH/USDT', 'name': 'Ethereum', 'group': 'core'},
 'BNB': {'pair': 'BNB/USDT', 'name': 'BNB', 'group': 'core'},
 'XRP': {'pair': 'XRP/USDT', 'name': 'XRP', 'group': 'core'},
 'SOL': {'pair': 'SOL/USDT', 'name': 'Solana', 'group': 'core'},
 'TRX': {'pair': 'TRX/USDT', 'name': 'TRON', 'group': 'core'},
 'DOGE': {'pair': 'DOGE/USDT', 'name': 'Dogecoin', 'group': 'core'},
 'ADA': {'pair': 'ADA/USDT', 'name': 'Cardano', 'group': 'core'},
 'LINK': {'pair': 'LINK/USDT', 'name': 'Chainlink', 'group': 'core'},
 'AVAX': {'pair': 'AVAX/USDT', 'name': 'Avalanche', 'group': 'core'},
 'DOT': {'pair': 'DOT/USDT', 'name': 'Polkadot', 'group': 'core'},
 'LTC': {'pair': 'LTC/USDT', 'name': 'Litecoin', 'group': 'large'},
 'BCH': {'pair': 'BCH/USDT', 'name': 'Bitcoin Cash', 'group': 'large'},
 'XLM': {'pair': 'XLM/USDT', 'name': 'Stellar', 'group': 'large'},
 'SUI': {'pair': 'SUI/USDT', 'name': 'Sui', 'group': 'large'},
 'TON': {'pair': 'TON/USDT', 'name': 'Toncoin', 'group': 'large'},
 'HBAR': {'pair': 'HBAR/USDT', 'name': 'Hedera', 'group': 'large'},
 'SHIB': {'pair': 'SHIB/USDT', 'name': 'Shiba Inu', 'group': 'large'},
 'UNI': {'pair': 'UNI/USDT', 'name': 'Uniswap', 'group': 'defi'},
 'AAVE': {'pair': 'AAVE/USDT', 'name': 'Aave', 'group': 'defi'},
 'NEAR': {'pair': 'NEAR/USDT', 'name': 'NEAR Protocol', 'group': 'large'},
 'ATOM': {'pair': 'ATOM/USDT', 'name': 'Cosmos', 'group': 'large'},
 'FIL': {'pair': 'FIL/USDT', 'name': 'Filecoin', 'group': 'large'},
 'ETC': {'pair': 'ETC/USDT', 'name': 'Ethereum Classic', 'group': 'large'},
 'ARB': {'pair': 'ARB/USDT', 'name': 'Arbitrum', 'group': 'layer2'},
 'OP': {'pair': 'OP/USDT', 'name': 'Optimism', 'group': 'layer2'},
 'APT': {'pair': 'APT/USDT', 'name': 'Aptos', 'group': 'large'},
 'INJ': {'pair': 'INJ/USDT', 'name': 'Injective', 'group': 'defi'},
 'RENDER': {'pair': 'RENDER/USDT', 'name': 'Render', 'group': 'ai'},
 'FET': {'pair': 'FET/USDT', 'name': 'Artificial Superintelligence Alliance', 'group': 'ai'},
 'ICP': {'pair': 'ICP/USDT', 'name': 'ICP', 'group': 'large'},
 'ALGO': {'pair': 'ALGO/USDT', 'name': 'ALGO', 'group': 'large'},
 'VET': {'pair': 'VET/USDT', 'name': 'VET', 'group': 'large'},
 'IMX': {'pair': 'IMX/USDT', 'name': 'IMX', 'group': 'layer2'},
 'STX': {'pair': 'STX/USDT', 'name': 'STX', 'group': 'large'},
 'LDO': {'pair': 'LDO/USDT', 'name': 'LDO', 'group': 'defi'},
 'RUNE': {'pair': 'RUNE/USDT', 'name': 'RUNE', 'group': 'large'},
 'GRT': {'pair': 'GRT/USDT', 'name': 'GRT', 'group': 'large'},
 'THETA': {'pair': 'THETA/USDT', 'name': 'THETA', 'group': 'large'},
 'EGLD': {'pair': 'EGLD/USDT', 'name': 'EGLD', 'group': 'large'},
 'XTZ': {'pair': 'XTZ/USDT', 'name': 'XTZ', 'group': 'large'},
 'SEI': {'pair': 'SEI/USDT', 'name': 'SEI', 'group': 'large'},
 'TIA': {'pair': 'TIA/USDT', 'name': 'TIA', 'group': 'large'},
 'PYTH': {'pair': 'PYTH/USDT', 'name': 'PYTH', 'group': 'oracle'},
 'WLD': {'pair': 'WLD/USDT', 'name': 'WLD', 'group': 'ai'},
 'TAO': {'pair': 'TAO/USDT', 'name': 'TAO', 'group': 'ai'},
 'ARKM': {'pair': 'ARKM/USDT', 'name': 'ARKM', 'group': 'ai'},
 'ONDO': {'pair': 'ONDO/USDT', 'name': 'ONDO', 'group': 'rwa'},
 'ENA': {'pair': 'ENA/USDT', 'name': 'ENA', 'group': 'defi'},
 'PENDLE': {'pair': 'PENDLE/USDT', 'name': 'PENDLE', 'group': 'defi'},
 'MORPHO': {'pair': 'MORPHO/USDT', 'name': 'MORPHO', 'group': 'defi'},
 'ETHFI': {'pair': 'ETHFI/USDT', 'name': 'ETHFI', 'group': 'defi'},
 'EIGEN': {'pair': 'EIGEN/USDT', 'name': 'EIGEN', 'group': 'defi'},
 'JTO': {'pair': 'JTO/USDT', 'name': 'JTO', 'group': 'defi'},
 'STRK': {'pair': 'STRK/USDT', 'name': 'STRK', 'group': 'layer2'},
 'ZK': {'pair': 'ZK/USDT', 'name': 'ZK', 'group': 'layer2'},
 'METIS': {'pair': 'METIS/USDT', 'name': 'METIS', 'group': 'layer2'},
 'MANTA': {'pair': 'MANTA/USDT', 'name': 'MANTA', 'group': 'layer2'},
 'POL': {'pair': 'POL/USDT', 'name': 'POL', 'group': 'layer2'},
 'CRV': {'pair': 'CRV/USDT', 'name': 'CRV', 'group': 'defi'},
 'COMP': {'pair': 'COMP/USDT', 'name': 'COMP', 'group': 'defi'},
 'SNX': {'pair': 'SNX/USDT', 'name': 'SNX', 'group': 'large'},
 'DYDX': {'pair': 'DYDX/USDT', 'name': 'DYDX', 'group': 'defi'},
 'SUSHI': {'pair': 'SUSHI/USDT', 'name': 'SUSHI', 'group': 'defi'},
 'CAKE': {'pair': 'CAKE/USDT', 'name': 'CAKE', 'group': 'defi'},
 'RAY': {'pair': 'RAY/USDT', 'name': 'RAY', 'group': 'defi'},
 'GALA': {'pair': 'GALA/USDT', 'name': 'GALA', 'group': 'gaming'},
 'SAND': {'pair': 'SAND/USDT', 'name': 'SAND', 'group': 'gaming'},
 'MANA': {'pair': 'MANA/USDT', 'name': 'MANA', 'group': 'gaming'},
 'AXS': {'pair': 'AXS/USDT', 'name': 'AXS', 'group': 'gaming'},
 'ILV': {'pair': 'ILV/USDT', 'name': 'ILV', 'group': 'gaming'},
 'YGG': {'pair': 'YGG/USDT', 'name': 'YGG', 'group': 'gaming'},
 'SUPER': {'pair': 'SUPER/USDT', 'name': 'SUPER', 'group': 'gaming'},
 'RONIN': {'pair': 'RONIN/USDT', 'name': 'RONIN', 'group': 'gaming'},
 'AR': {'pair': 'AR/USDT', 'name': 'AR', 'group': 'depin'},
 'STORJ': {'pair': 'STORJ/USDT', 'name': 'STORJ', 'group': 'storage'},
 'IOTX': {'pair': 'IOTX/USDT', 'name': 'IOTX', 'group': 'depin'},
 'IO': {'pair': 'IO/USDT', 'name': 'IO', 'group': 'ai'},
 'BAND': {'pair': 'BAND/USDT', 'name': 'BAND', 'group': 'oracle'},
 'API3': {'pair': 'API3/USDT', 'name': 'API3', 'group': 'oracle'},
 'PEPE': {'pair': 'PEPE/USDT', 'name': 'PEPE', 'group': 'meme'},
 'BONK': {'pair': 'BONK/USDT', 'name': 'BONK', 'group': 'meme'},
 'FLOKI': {'pair': 'FLOKI/USDT', 'name': 'FLOKI', 'group': 'meme'},
 'WIF': {'pair': 'WIF/USDT', 'name': 'WIF', 'group': 'meme'},
 'PENGU': {'pair': 'PENGU/USDT', 'name': 'PENGU', 'group': 'meme'},
 'VIRTUAL': {'pair': 'VIRTUAL/USDT', 'name': 'VIRTUAL', 'group': 'ai'},
 'ZEC': {'pair': 'ZEC/USDT', 'name': 'ZEC', 'group': 'large'},
 'DASH': {'pair': 'DASH/USDT', 'name': 'DASH', 'group': 'large'},
 'ONE': {'pair': 'ONE/USDT', 'name': 'ONE', 'group': 'large'},
 'BLUR': {'pair': 'BLUR/USDT', 'name': 'BLUR', 'group': 'large'},
 'ACE': {'pair': 'ACE/USDT', 'name': 'ACE', 'group': 'large'},
 'PROM': {'pair': 'PROM/USDT', 'name': 'PROM', 'group': 'large'},
 'KAVA': {'pair': 'KAVA/USDT', 'name': 'KAVA', 'group': 'large'},
 'MINA': {'pair': 'MINA/USDT', 'name': 'MINA', 'group': 'large'},
 'ROSE': {'pair': 'ROSE/USDT', 'name': 'ROSE', 'group': 'large'},
 'CELO': {'pair': 'CELO/USDT', 'name': 'CELO', 'group': 'large'},
 'ZIL': {'pair': 'ZIL/USDT', 'name': 'ZIL', 'group': 'large'},
 'QTUM': {'pair': 'QTUM/USDT', 'name': 'QTUM', 'group': 'large'},
 'IOTA': {'pair': 'IOTA/USDT', 'name': 'IOTA', 'group': 'large'},
 'NEO': {'pair': 'NEO/USDT', 'name': 'NEO', 'group': 'large'}}

CRYPTO_PAIRS = {
    code: item['pair']
    for code, item in CRYPTO_UNIVERSE.items()
}

def get_bist_universe(name: str):
    return BIST_UNIVERSES.get(name, [])

def get_crypto_pairs(group: str | None = None):
    if not group or group == 'Hepsi':
        return CRYPTO_PAIRS.copy()

    return {
        code: item['pair']
        for code, item in CRYPTO_UNIVERSE.items()
        if item.get('group') == group
    }

def get_crypto_groups():
    groups = sorted({item['group'] for item in CRYPTO_UNIVERSE.values()})
    return ['Hepsi', *groups]